import React, { useEffect, useState } from 'react';

const IntroAnimation = ({ onComplete }) => {
    const [visible, setVisible] = useState(true);

    useEffect(() => {
        const createDotsAnimation = () => {
            const container = document.getElementById('dotsContainer');
            if (!container) return;

            const dots = [
                // Main circuit nodes
                { x: 50, y: 50 }, { x: 120, y: 50 }, { x: 200, y: 50 }, { x: 280, y: 50 }, { x: 350, y: 50 },
                { x: 50, y: 100 }, { x: 120, y: 100 }, { x: 200, y: 100 }, { x: 280, y: 100 }, { x: 350, y: 100 },
                { x: 50, y: 150 }, { x: 120, y: 150 }, { x: 200, y: 150 }, { x: 280, y: 150 }, { x: 350, y: 150 },
                { x: 50, y: 200 }, { x: 120, y: 200 }, { x: 200, y: 200 }, { x: 280, y: 200 }, { x: 350, y: 200 },
                { x: 50, y: 250 }, { x: 120, y: 250 }, { x: 200, y: 250 }, { x: 280, y: 250 }, { x: 350, y: 250 },
                // Additional nodes for complexity
                { x: 85, y: 75 }, { x: 160, y: 75 }, { x: 240, y: 75 }, { x: 315, y: 75 },
                { x: 85, y: 125 }, { x: 160, y: 125 }, { x: 240, y: 125 }, { x: 315, y: 125 },
                { x: 85, y: 175 }, { x: 160, y: 175 }, { x: 240, y: 175 }, { x: 315, y: 175 },
                { x: 85, y: 225 }, { x: 160, y: 225 }, { x: 240, y: 225 }, { x: 315, y: 225 }
            ];

            const connections = [
                // Horizontal connections
                [0, 1], [1, 2], [2, 3], [3, 4], [5, 6], [6, 7], [7, 8], [8, 9],
                [10, 11], [11, 12], [12, 13], [13, 14], [15, 16], [16, 17], [17, 18], [18, 19],
                [20, 21], [21, 22], [22, 23], [23, 24],
                // Vertical connections
                [0, 5], [1, 6], [2, 7], [3, 8], [4, 9], [5, 10], [6, 11], [7, 12], [8, 13], [9, 14],
                [10, 15], [11, 16], [12, 17], [13, 18], [14, 19], [15, 20], [16, 21], [17, 22], [18, 23], [19, 24],
                // Diagonal connections
                [0, 25], [1, 26], [2, 27], [3, 28], [5, 29], [6, 30], [7, 31], [8, 32],
                [10, 33], [11, 34], [12, 35], [13, 36], [15, 37], [16, 38], [17, 39], [18, 40],
                // Inter-diagonal connections
                [25, 6], [26, 7], [27, 8], [28, 9], [29, 11], [30, 12], [31, 13], [32, 14],
                [33, 16], [34, 17], [35, 18], [36, 19], [37, 21], [38, 22], [39, 23], [40, 24],
                // Cross connections
                [25, 29], [26, 30], [27, 31], [28, 32], [29, 33], [30, 34], [31, 35], [32, 36],
                [33, 37], [34, 38], [35, 39], [36, 40],
                // Additional complex paths
                [0, 29], [4, 32], [20, 38], [24, 40], [25, 35], [28, 34], [26, 36], [27, 33]
            ];

            // Clear container
            container.innerHTML = '';

            // Create dots
            dots.forEach((dot, index) => {
                const dotElement = document.createElement('div');
                dotElement.className = 'dot';
                dotElement.style.left = dot.x + 'px';
                dotElement.style.top = dot.y + 'px';
                dotElement.style.animationDelay = index * 0.1 + 's';
                container.appendChild(dotElement);
            });

            // Create connections
            connections.forEach((connection, index) => {
                const [start, end] = connection;
                const startDot = dots[start];
                const endDot = dots[end];

                const line = document.createElement('div');
                line.className = 'connection-line';

                const distance = Math.sqrt(
                    Math.pow(endDot.x - startDot.x, 2) +
                    Math.pow(endDot.y - startDot.y, 2)
                );

                const angle = Math.atan2(endDot.y - startDot.y, endDot.x - startDot.x);

                line.style.width = distance + 'px';
                line.style.left = startDot.x + 'px';
                line.style.top = startDot.y + 'px';
                line.style.transform = `rotate(${angle}rad)`;
                line.style.transformOrigin = '0 50%';
                line.style.animationDelay = (dots.length * 0.1 + index * 0.05) + 's';

                container.appendChild(line);
            });

            // Hide intro after animation
            setTimeout(() => {
                setVisible(false);
                if (onComplete) onComplete();
            }, 4000);
        };

        createDotsAnimation();
    }, [onComplete]);

    if (!visible) return null;

    return (
        <div className={`intro-screen ${!visible ? 'fade-out' : ''}`} id="introScreen">
            <div className="dots-container" id="dotsContainer">
                {/* Dots and lines generated by JS */}
            </div>
        </div>
    );
};

export default IntroAnimation;
